---
- hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: "Validate and create an object"
      panos_address_object:
        ip_address: "10.0.131.80"
        api_key: "LUFRPT1uNGEvNVhlQzZadmpPUkgyUjRKUGRFdzhuVmM9M1hpNTlUWVJjZWFoTy8ycCtmRHJoaHIyU1hBM1FXL1hUbzNGMGFvbm1kVzNUeThDWEVRQmVEQnA2aTBqT0RMaQ=="
        name: "{{ object_name }}"
        address_type: "fqdn"
        value: "gaming.redtail.com"
        description: "{{ object_description }}"
        device_group: "AL-PA5220"

    - name: Commit changes on Panorama
      panos_commit:
        ip_address: "10.0.131.80"
        api_key: "LUFRPT1uNGEvNVhlQzZadmpPUkgyUjRKUGRFdzhuVmM9M1hpNTlUWVJjZWFoTy8ycCtmRHJoaHIyU1hBM1FXL1hUbzNGMGFvbm1kVzNUeThDWEVRQmVEQnA2aTBqT0RMaQ=="
        
    - name: Debug API response
      debug:
        var: response
